# Generated by Django 4.2.13 on 2024-06-09 09:39

from django.db import migrations, models
import django.db.models.deletion
import school.cdn.backends


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_auth_method_remove_user_creationdate_and_more'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFinalAnswer',
            fields=[
                ('adminanswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.adminanswer')),
            ],
            bases=('quiz.adminanswer',),
        ),
        migrations.CreateModel(
            name='AdminMultipleChoiceAnswer',
            fields=[
                ('adminanswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.adminanswer')),
                ('image', models.ImageField(blank=True, null=True, storage=school.cdn.backends.MediaRootS3Boto3Storage(), upload_to='')),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
            ],
            bases=('quiz.adminanswer',),
        ),
        migrations.CreateModel(
            name='H1',
            fields=[
                ('headbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.headbase')),
            ],
            options={
                'ordering': ['lesson', 'order'],
            },
            bases=('quiz.headbase',),
        ),
        migrations.CreateModel(
            name='HeadLine',
            fields=[
                ('headbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.headbase')),
                ('level', models.IntegerField(blank=True, choices=[(2, 'H2'), (3, 'H3'), (4, 'H4'), (5, 'H5')], null=True)),
            ],
            options={
                'ordering': ['parent_headline', 'order'],
            },
            bases=('quiz.headbase',),
        ),
        migrations.CreateModel(
            name='UserFinalAnswer',
            fields=[
                ('useranswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.useranswer')),
                ('body', models.TextField(blank=True, null=True)),
            ],
            bases=('quiz.useranswer',),
        ),
        migrations.CreateModel(
            name='UserMultipleChoiceAnswer',
            fields=[
                ('useranswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.useranswer')),
                ('choice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.adminmultiplechoiceanswer')),
            ],
            bases=('quiz.useranswer',),
        ),
        migrations.CreateModel(
            name='UserMultiSectionAnswer',
            fields=[
                ('useranswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.useranswer')),
            ],
            bases=('quiz.useranswer',),
        ),
        migrations.CreateModel(
            name='UserWritingAnswer',
            fields=[
                ('useranswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.useranswer')),
                ('answer', models.ImageField(blank=True, null=True, storage=school.cdn.backends.MediaRootS3Boto3Storage(), upload_to='')),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'waiting'), (1, 'done')], null=True)),
            ],
            bases=('quiz.useranswer',),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['module', 'order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='adminquiz',
            name='questions',
            field=models.ManyToManyField(blank=True, to='quiz.question'),
        ),
        migrations.AddField(
            model_name='headbase',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headlineinst',
            name='headline',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.headbase'),
        ),
        migrations.AddField(
            model_name='headlineinst',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.module'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='subject',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.subject'),
        ),
        migrations.AddField(
            model_name='multisectionquestion',
            name='is_extraction_question',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='multisectionquestion',
            name='sub_questions',
            field=models.ManyToManyField(blank=True, related_name='sections', to='quiz.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='quiz.tag'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.subject'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.question'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='quiz',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.userquiz'),
        ),
        migrations.AddField(
            model_name='userquiz',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
        migrations.DeleteModel(
            name='SavedQuestion',
        ),
        migrations.AddField(
            model_name='usermultisectionanswer',
            name='sub_questions_answers',
            field=models.ManyToManyField(blank=True, related_name='sections_answers', to='quiz.useranswer'),
        ),
        migrations.AddField(
            model_name='headline',
            name='parent_headline',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_headings', to='quiz.headbase'),
        ),
        migrations.AddField(
            model_name='h1',
            name='lesson',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.lesson'),
        ),
        migrations.AddField(
            model_name='finalanswerquestion',
            name='correct_answer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.adminfinalanswer'),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='choices', to='quiz.adminmultiplechoiceanswer'),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='correct_answer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='quiz.adminmultiplechoiceanswer'),
        ),
    ]
