# Generated by Django 4.2.13 on 2025-05-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.FloatField(blank=True, default=2.0),
        ),
    ]
