# Generated by Django 4.2.13 on 2025-05-18 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_advertisement_ad'),
        ('quiz', '0003_alter_question_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReelQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.question')),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('correct_answer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.adminfinalanswer')),
            ],
            bases=('quiz.question',),
        ),
        migrations.CreateModel(
            name='ReelInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('last_view_at', models.DateTimeField(blank=True, null=True)),
                ('taps', models.PositiveIntegerField(default=0)),
                ('last_tap', models.DateTimeField(blank=True, null=True)),
                ('favorite', models.BooleanField(default=False)),
                ('reel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.reelquestion')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
            options={
                'unique_together': {('user', 'reel')},
            },
        ),
    ]
