# Generated by Django 4.2.13 on 2025-05-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_reelquestion_reelinteraction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reelinteraction',
            old_name='last_tap',
            new_name='last_tap_at',
        ),
    ]
