# Generated by Django 4.2.13 on 2025-05-19 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_rename_last_tap_reelinteraction_last_tap_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeSubject',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.tag')),
                ('grade', models.IntegerField(blank=True, null=True)),
            ],
            bases=('quiz.tag',),
        ),
    ]
