# Generated by Django 4.2.13 on 2025-05-19 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_fakesubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='f_subject',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.fakesubject'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='fsubject',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.fakesubject'),
        ),
    ]
