# Generated by Django 4.2.13 on 2025-05-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_remove_packages_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='f_subject',
            new_name='subject',
        ),
    ]
