# Generated by Django 4.2.13 on 2025-05-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_remove_quiz_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='fsubject',
            new_name='subject',
        ),
    ]
