# Generated by Django 4.2.13 on 2025-05-19 15:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_rename_fsubject_quiz_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('semester', models.IntegerField(blank=True, choices=[(1, 'الفصل الأول'), (2, 'الفصل الثاني')], null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('subject', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.fakesubject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
