# Generated by Django 4.2.13 on 2025-05-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_fakemodule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
