# Generated by Django 4.2.13 on 2025-05-19 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_remove_module_subject_delete_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaModule',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.tag')),
                ('semester', models.IntegerField(blank=True, choices=[(1, 'الفصل الأول'), (2, 'الفصل الثاني')], null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('subject', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.fakesubject')),
            ],
            options={
                'ordering': ['order'],
            },
            bases=('quiz.tag',),
        ),
    ]
