# Generated by Django 4.2.13 on 2025-05-19 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_famodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaLesson',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.tag')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('module', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.famodule')),
            ],
            options={
                'ordering': ['module', 'order'],
            },
            bases=('quiz.tag',),
        ),
        migrations.DeleteModel(
            name='FakeModule',
        ),
    ]
