# Generated by Django 4.2.13 on 2025-05-19 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_alter_lesson_options_remove_lesson_module_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='h1',
            options={'ordering': ['fa_lesson', 'order']},
        ),
        migrations.RemoveField(
            model_name='h1',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
