# Generated by Django 4.2.13 on 2025-05-19 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_alter_h1_options_remove_h1_lesson_delete_lesson'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FakeSubject',
            new_name='Subject',
        ),
        migrations.AlterModelOptions(
            name='falesson',
            options={'ordering': ['parent_module', 'order']},
        ),
        migrations.AlterModelOptions(
            name='h1',
            options={'ordering': ['parent_lesson', 'order']},
        ),
        migrations.RenameField(
            model_name='falesson',
            old_name='module',
            new_name='parent_module',
        ),
        migrations.RenameField(
            model_name='famodule',
            old_name='subject',
            new_name='parent_subject',
        ),
        migrations.RenameField(
            model_name='h1',
            old_name='fa_lesson',
            new_name='parent_lesson',
        ),
    ]
