# Generated by Django 4.2.13 on 2025-05-19 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_rename_fakesubject_subject_alter_falesson_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FaModule',
            new_name='Module',
        ),
    ]
