# Generated by Django 4.2.13 on 2025-05-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_rename_famodule_module'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FaLesson',
            new_name='Lesson',
        ),
    ]
