# Generated by Django 4.2.13 on 2025-05-24 21:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_ad_external_link'),
        ('quiz', '0020_rename_falesson_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageActivationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('code', models.CharField(editable=False, max_length=100, unique=True)),
                ('used_date', models.DateTimeField(blank=True, null=True)),
                ('pkgs', models.ManyToManyField(blank=True, to='quiz.packages')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
    ]
