# Generated by Django 4.2.13 on 2025-06-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_packageactivationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_hidden',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_hidden',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
