# Generated by Django 4.2.13 on 2025-06-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_question_is_hidden_tag_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='app_store_product_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
