# Generated by Django 4.2.13 on 2025-08-03 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_packages_app_store_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalanswerquestion',
            name='correct_answer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.adminfinalanswer'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='correct_answer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correct_answer', to='quiz.adminmultiplechoiceanswer'),
        ),
        migrations.AlterField(
            model_name='reelquestion',
            name='correct_answer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.adminfinalanswer'),
        ),
    ]
