# Generated by Django 4.2.13 on 2025-05-04 18:28

from django.db import migrations, models
import django.db.models.deletion
import school.cdn.backends
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, storage=school.cdn.backends.MediaRootS3Boto3Storage(), upload_to='')),
                ('active', models.BooleanField(default=False, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, storage=school.cdn.backends.MediaRootS3Boto3Storage(), upload_to='')),
                ('creationDate', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('userUID', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('firstName', models.CharField(blank=True, max_length=30, null=True)),
                ('lastName', models.CharField(blank=True, max_length=30, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('school_name', models.CharField(blank=True, max_length=100, null=True)),
                ('listenFrom', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_method', models.CharField(blank=True, max_length=50, null=True)),
                ('admin', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('shared_limit', models.IntegerField(blank=True, default=0)),
                ('pkg_list', models.ManyToManyField(blank=True, to='quiz.packages')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
