# Generated by Django 4.2.4 on 2024-06-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_method',
        ),
        migrations.RemoveField(
            model_name='user',
            name='creationDate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='userUID',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='DailyTask',
        ),
    ]
