# Generated by Django 4.2.13 on 2024-06-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_auth_method_remove_user_creationdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
