# Generated by Django 4.2.13 on 2025-05-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_anonymous_user_password_user_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertisement',
            new_name='Ad',
        ),
    ]
