# Generated by Django 4.2.13 on 2025-05-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_advertisement_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='external_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
