# Generated by Django 4.2.13 on 2025-06-26 20:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_question_is_hidden_tag_is_hidden'),
        ('user', '0004_ad_external_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creationDate', models.DateField(auto_now_add=True, null=True)),
                ('source', models.IntegerField(blank=True, choices=[(1, 'apple'), (2, 'google'), (3, 'direct')], null=True)),
                ('item', models.ManyToManyField(blank=True, to='quiz.packages')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
    ]
