# Generated by Django 4.2.13 on 2025-06-26 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='item',
            new_name='items',
        ),
    ]
