# Generated by Django 4.2.13 on 2025-07-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_item_transaction_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ad',
            new_name='Banner',
        ),
    ]
