# Generated by Django 4.2.13 on 2025-07-15 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_ad_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='creationDate',
            new_name='created_at',
        ),
    ]
