# Generated by Django 4.2.13 on 2025-07-15 12:48

from django.db import migrations, models
import school.cdn.backends


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_creationdate_banner_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_web',
            field=models.ImageField(blank=True, null=True, storage=school.cdn.backends.MediaRootS3Boto3Storage(), upload_to=''),
        ),
    ]
