# Generated by Django 4.2.13 on 2025-07-15 12:48

from django.db import migrations, models
import school.cdn.backends


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_banner_image_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='Image used in mobile app', null=True, storage=school.cdn.backends.MediaRootS3Boto3Storage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_web',
            field=models.ImageField(blank=True, help_text='Image used in web interface', null=True, storage=school.cdn.backends.MediaRootS3Boto3Storage(), upload_to=''),
        ),
    ]
